[window]

opacity = 0.95

padding.x = 20
padding.y = 20


[font]

normal.family = "Victor Mono NFP Medium"
normal.style = "medium"

size = 14.0

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.

[colors.primary]
background = "#ece9e9"
foreground = "#5c6a72"
dim_foreground = "#8c8fa1"
bright_foreground = "#4c4f69"

  [colors.normal]
    black   = '#5c6a72'
    red     = '#f85552'
    green   = '#8da101'
    yellow  = '#dfa000'
    blue    = '#3a94c5'
    magenta = '#df69ba'
    cyan    = '#35a77c'
    white   = '#e8e5d5'

  [colors.bright]
    black   = '#5c6a72'
    red     = '#f85552'
    green   = '#8da101'
    yellow  = '#dfa000'
    blue    = '#3a94c5'
    magenta = '#df69ba'
    cyan    = '#35a77c'
    white   = '#e8e5d5'

  [colors.cursor]
    text = '#fffbef'    # Cursor text matches the background
    cursor = '#5c6a72'  # Cursor foreground color

  [colors.selection]
    text = '#5c6a72'        # Text color for selected text
    background = '#f3ead3'  # Selection background color
